# Generated by Django 2.2.17 on 2020-12-03 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, verbose_name='邀请码')),
                ('company', models.CharField(blank=True, max_length=128, verbose_name='公司')),
                ('active', models.BooleanField(default=True, verbose_name='可用')),
            ],
            options={
                'verbose_name': '邀请码',
            },
        ),
        migrations.CreateModel(
            name='InviteCodeBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '邀请码批量生成器(点我, 不允许在上面单独添加邀请码)',
                'permissions': (('batch_create', '批量创建'),),
            },
        ),
    ]
