# Generated by Django 2.2.17 on 2020-12-02 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteCodeBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '邀请码批量生成器(点我, 不允许在上面单独添加邀请码)',
                'permissions': (('batch_create', '批量创建'),),
            },
        ),
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, verbose_name='邀请码')),
                ('company', models.CharField(blank=True, max_length=128, verbose_name='公司')),
                ('active', models.BooleanField(default=True, verbose_name='可用')),
                ('creater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitecode_creater', to='main_user.Users')),
                ('users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_user.Users')),
            ],
            options={
                'verbose_name': '邀请码',
            },
        ),
    ]
