# Generated by Django 2.2.17 on 2020-12-03 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inviteCode', '0001_initial'),
        ('main_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitecode',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitecode_creater', to='main_user.Users'),
        ),
        migrations.AddField(
            model_name='invitecode',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_user.Users'),
        ),
    ]
