# Generated by Django 3.0.8 on 2020-07-22 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inviteCode', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitecode',
            options={'verbose_name': '激活码'},
        ),
    ]
