# Generated by Django 3.0.8 on 2020-08-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inviteCode', '0002_auto_20200722_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecode',
            name='code',
            field=models.CharField(blank=True, max_length=10, verbose_name='激活码'),
        ),
    ]
