# Generated by Django 3.0.8 on 2020-08-05 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inviteCode', '0004_invitecode_creater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecode',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitecode_creater', to=settings.AUTH_USER_MODEL),
        ),
    ]
