# Generated by Django 3.0.8 on 2020-09-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inviteCode', '0005_auto_20200805_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteCodeBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '邀请码批量生成器(点我, 不允许在上面单独添加邀请码)',
                'permissions': (('batch_create', '批量创建'),),
            },
        ),
        migrations.AlterModelOptions(
            name='invitecode',
            options={'verbose_name': '邀请码'},
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='code',
            field=models.CharField(blank=True, max_length=10, verbose_name='邀请码'),
        ),
    ]
