# Generated by Django 2.2.17 on 2020-12-03 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.TAIGA_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='projects', through='projects.Membership', to=settings.TAIGA_USER_MODEL, verbose_name='members'),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to=settings.TAIGA_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='priority',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priorities', to='projects.Project', verbose_name='project'),
        ),
        migrations.AddField(
            model_name='points',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='projects.Project', verbose_name='project'),
        ),
        migrations.AddField(
            model_name='membership',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ihaveinvited+', to=settings.TAIGA_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membership',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='projects.Project'),
        ),
        migrations.AddField(
            model_name='membership',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='users.Role'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.TAIGA_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issuetype',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_types', to='projects.Project', verbose_name='project'),
        ),
        migrations.AddField(
            model_name='issuestatus',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_statuses', to='projects.Project', verbose_name='project'),
        ),
        migrations.AddField(
            model_name='issueduedate',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_duedates', to='projects.Project', verbose_name='project'),
        ),
        migrations.AddField(
            model_name='epicstatus',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epic_statuses', to='projects.Project', verbose_name='project'),
        ),
        migrations.AlterUniqueTogether(
            name='userstorystatus',
            unique_together={('project', 'name'), ('project', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='userstoryduedate',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='taskstatus',
            unique_together={('project', 'name'), ('project', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='taskduedate',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='severity',
            unique_together={('project', 'name')},
        ),
        migrations.AlterIndexTogether(
            name='project',
            index_together={('name', 'id')},
        ),
        migrations.AlterUniqueTogether(
            name='priority',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='points',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('user', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='issuetype',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='issuestatus',
            unique_together={('project', 'name'), ('project', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='issueduedate',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='epicstatus',
            unique_together={('project', 'name'), ('project', 'slug')},
        ),
    ]
