# Generated by Django 2.2.17 on 2020-12-03 02:19

import django.core.serializers.json
from django.db import migrations, models
import django.utils.timezone
import taiga.base.db.models.fields.json
import taiga.projects.history.choices
import taiga.projects.notifications.choices


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryChangeNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(editable=False, max_length=255)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='created date time')),
                ('updated_datetime', models.DateTimeField(auto_now_add=True, verbose_name='updated date time')),
                ('history_type', models.SmallIntegerField(choices=[(taiga.projects.history.choices.HistoryType(1), 'Change'), (taiga.projects.history.choices.HistoryType(2), 'Create'), (taiga.projects.history.choices.HistoryType(3), 'Delete')])),
            ],
        ),
        migrations.CreateModel(
            name='NotifyPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_level', models.SmallIntegerField(choices=[(taiga.projects.notifications.choices.NotifyLevel(1), 'Involved'), (taiga.projects.notifications.choices.NotifyLevel(2), 'All'), (taiga.projects.notifications.choices.NotifyLevel(3), 'None')])),
                ('live_notify_level', models.SmallIntegerField(choices=[(taiga.projects.notifications.choices.NotifyLevel(1), 'Involved'), (taiga.projects.notifications.choices.NotifyLevel(2), 'All'), (taiga.projects.notifications.choices.NotifyLevel(3), 'None')], default=taiga.projects.notifications.choices.NotifyLevel(1))),
                ('web_notify_level', models.BooleanField(blank=True, default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Watched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
            ],
            options={
                'verbose_name': 'Watched',
                'verbose_name_plural': 'Watched',
            },
        ),
        migrations.CreateModel(
            name='WebNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('read', models.DateTimeField(default=None, null=True)),
                ('event_type', models.PositiveIntegerField()),
                ('data', taiga.base.db.models.fields.json.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
        ),
    ]
