# Generated by Django 2.2.17 on 2020-12-03 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_auto_20201203_1019'),
        migrations.swappable_dependency(settings.TAIGA_USER_MODEL),
        ('notifications', '0001_initial'),
        ('history', '0002_historyentry_project'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='webnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_notifications', to=settings.TAIGA_USER_MODEL),
        ),
        migrations.AddField(
            model_name='watched',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='watched',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched', to='projects.Project', verbose_name='project'),
        ),
        migrations.AddField(
            model_name='watched',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched', to=settings.TAIGA_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='notifypolicy',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_policies', to='projects.Project'),
        ),
        migrations.AddField(
            model_name='notifypolicy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_policies', to=settings.TAIGA_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historychangenotification',
            name='history_entries',
            field=models.ManyToManyField(related_name='_historychangenotification_history_entries_+', to='history.HistoryEntry', verbose_name='history entries'),
        ),
        migrations.AddField(
            model_name='historychangenotification',
            name='notify_users',
            field=models.ManyToManyField(related_name='_historychangenotification_notify_users_+', to=settings.TAIGA_USER_MODEL, verbose_name='notify users'),
        ),
        migrations.AddField(
            model_name='historychangenotification',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.TAIGA_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='historychangenotification',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='projects.Project', verbose_name='project'),
        ),
        migrations.AlterUniqueTogether(
            name='watched',
            unique_together={('content_type', 'object_id', 'user', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='notifypolicy',
            unique_together={('project', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='historychangenotification',
            unique_together={('key', 'owner', 'project', 'history_type')},
        ),
    ]
