# Generated by Django 2.2.17 on 2020-12-03 02:19

import django.core.serializers.json
from django.db import migrations, models
import django.utils.timezone
import taiga.base.db.models.fields.json
import taiga.projects.history.choices
import taiga.projects.history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryEntry',
            fields=[
                ('id', models.CharField(default=taiga.projects.history.models._generate_uuid, editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('user', taiga.base.db.models.fields.json.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.SmallIntegerField(choices=[(taiga.projects.history.choices.HistoryType(1), 'Change'), (taiga.projects.history.choices.HistoryType(2), 'Create'), (taiga.projects.history.choices.HistoryType(3), 'Delete')])),
                ('key', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('diff', taiga.base.db.models.fields.json.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('values_diff_cache', taiga.base.db.models.fields.json.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('snapshot', taiga.base.db.models.fields.json.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('values', taiga.base.db.models.fields.json.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('comment', models.TextField(blank=True)),
                ('comment_html', models.TextField(blank=True)),
                ('delete_comment_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('delete_comment_user', taiga.base.db.models.fields.json.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('comment_versions', taiga.base.db.models.fields.json.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('edit_comment_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_snapshot', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
