# Generated by Django 2.2.17 on 2020-12-03 02:19

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import taiga.base.db.models.fields.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.TAIGA_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified date')),
                ('key', models.CharField(max_length=255, verbose_name='key')),
                ('value', taiga.base.db.models.fields.json.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='value')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_entries', to=settings.TAIGA_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'storage entry',
                'verbose_name_plural': 'storages entries',
                'ordering': ['owner', 'key'],
                'unique_together': {('owner', 'key')},
            },
        ),
    ]
