# Generated by Django 2.2.17 on 2020-12-03 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taiga.base.utils.time
import taiga.projects.notifications.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.TAIGA_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1, verbose_name='version')),
                ('slug', models.SlugField(allow_unicode=True, max_length=500, verbose_name='slug')),
                ('content', models.TextField(blank=True, verbose_name='content')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date')),
                ('modified_date', models.DateTimeField(verbose_name='modified date')),
                ('last_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_wiki_pages', to=settings.TAIGA_USER_MODEL, verbose_name='last modifier')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_wiki_pages', to=settings.TAIGA_USER_MODEL, verbose_name='owner')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiki_pages', to='projects.Project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'wiki page',
                'verbose_name_plural': 'wiki pages',
                'ordering': ['project', 'slug'],
                'unique_together': {('project', 'slug')},
            },
            bases=(taiga.projects.notifications.mixins.WatchedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WikiLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('href', models.SlugField(max_length=500, verbose_name='href')),
                ('order', models.BigIntegerField(default=taiga.base.utils.time.timestamp_ms, verbose_name='order')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiki_links', to='projects.Project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'wiki link',
                'verbose_name_plural': 'wiki links',
                'ordering': ['project', 'order', 'id'],
                'unique_together': {('project', 'href')},
            },
        ),
    ]
