# Generated by Django 2.2.17 on 2020-12-03 02:19

from django.db import migrations, models
import django.db.models.deletion
import taiga.external_apps.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.CharField(default=taiga.external_apps.models._generate_uuid, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('icon_url', models.TextField(blank=True, null=True, verbose_name='Icon url')),
                ('web', models.CharField(blank=True, max_length=255, null=True, verbose_name='web')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('next_url', models.TextField(verbose_name='Next url')),
            ],
            options={
                'verbose_name': 'application',
                'verbose_name_plural': 'applications',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_code', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('token', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_tokens', to='external_apps.Application', verbose_name='application')),
            ],
            options={
                'verbose_name': 'application token',
                'verbose_name_plural': 'application tokens',
                'ordering': ['application', 'user'],
            },
        ),
    ]
