# Generated by Django 2.2.17 on 2020-12-03 02:19

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taiga.base.utils.colors
import taiga.base.utils.time
import taiga.projects.notifications.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Epic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1, verbose_name='version')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, null=True, size=None, verbose_name='tags')),
                ('is_blocked', models.BooleanField(blank=True, default=False, verbose_name='is blocked')),
                ('blocked_note', models.TextField(blank=True, default='', verbose_name='blocked note')),
                ('ref', models.BigIntegerField(blank=True, db_index=True, default=None, null=True, verbose_name='ref')),
                ('epics_order', models.BigIntegerField(default=taiga.base.utils.time.timestamp_ms, verbose_name='epics order')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date')),
                ('modified_date', models.DateTimeField(verbose_name='modified date')),
                ('subject', models.TextField(verbose_name='subject')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('color', models.CharField(blank=True, default=taiga.base.utils.colors.generate_random_predefined_hex_color, max_length=32, verbose_name='color')),
                ('client_requirement', models.BooleanField(blank=True, default=False, verbose_name='is client requirement')),
                ('team_requirement', models.BooleanField(blank=True, default=False, verbose_name='is team requirement')),
                ('external_reference', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=None, null=True, size=None, verbose_name='external reference')),
            ],
            options={
                'verbose_name': 'epic',
                'verbose_name_plural': 'epics',
                'ordering': ['project', 'epics_order', 'ref'],
            },
            bases=(taiga.projects.notifications.mixins.WatchedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RelatedUserStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.BigIntegerField(default=taiga.base.utils.time.timestamp_ms, verbose_name='order')),
                ('epic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epics.Epic')),
            ],
            options={
                'verbose_name': 'related user story',
                'verbose_name_plural': 'related user stories',
                'ordering': ['user_story', 'order', 'id'],
            },
            bases=(taiga.projects.notifications.mixins.WatchedModelMixin, models.Model),
        ),
    ]
