# Generated by Django 2.2.17 on 2020-12-03 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('epics', '0001_initial'),
        ('projects', '0002_auto_20201203_1019'),
        ('userstories', '0001_initial'),
        migrations.swappable_dependency(settings.TAIGA_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='relateduserstory',
            name='user_story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userstories.UserStory'),
        ),
        migrations.AddField(
            model_name='epic',
            name='assigned_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epics_assigned_to_me', to=settings.TAIGA_USER_MODEL, verbose_name='assigned to'),
        ),
        migrations.AddField(
            model_name='epic',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_epics', to=settings.TAIGA_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='epic',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epics', to='projects.Project', verbose_name='project'),
        ),
        migrations.AddField(
            model_name='epic',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epics', to='projects.EpicStatus', verbose_name='status'),
        ),
        migrations.AddField(
            model_name='epic',
            name='user_stories',
            field=models.ManyToManyField(related_name='epics', through='epics.RelatedUserStory', to='userstories.UserStory', verbose_name='user stories'),
        ),
        migrations.AlterUniqueTogether(
            name='relateduserstory',
            unique_together={('user_story', 'epic')},
        ),
    ]
