# Generated by Django 2.2.17 on 2020-12-03 02:19

import django.core.serializers.json
from django.db import migrations, models
import django.utils.timezone
import taiga.base.db.models.fields.json
import taiga.base.utils.time


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EpicCustomAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('type', models.CharField(choices=[('text', 'Text'), ('multiline', 'Multi-Line Text'), ('richtext', 'Rich text'), ('date', 'Date'), ('url', 'Url'), ('dropdown', 'Dropdown'), ('checkbox', 'Checkbox'), ('number', 'Number')], default='text', max_length=16, verbose_name='type')),
                ('order', models.BigIntegerField(default=taiga.base.utils.time.timestamp_ms, verbose_name='order')),
                ('extra', taiga.base.db.models.fields.json.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date')),
                ('modified_date', models.DateTimeField(verbose_name='modified date')),
            ],
            options={
                'verbose_name': 'epic custom attribute',
                'verbose_name_plural': 'epic custom attributes',
                'ordering': ['project', 'order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EpicCustomAttributesValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1, verbose_name='version')),
                ('attributes_values', taiga.base.db.models.fields.json.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='values')),
            ],
            options={
                'verbose_name': 'epic custom attributes values',
                'verbose_name_plural': 'epic custom attributes values',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IssueCustomAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('type', models.CharField(choices=[('text', 'Text'), ('multiline', 'Multi-Line Text'), ('richtext', 'Rich text'), ('date', 'Date'), ('url', 'Url'), ('dropdown', 'Dropdown'), ('checkbox', 'Checkbox'), ('number', 'Number')], default='text', max_length=16, verbose_name='type')),
                ('order', models.BigIntegerField(default=taiga.base.utils.time.timestamp_ms, verbose_name='order')),
                ('extra', taiga.base.db.models.fields.json.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date')),
                ('modified_date', models.DateTimeField(verbose_name='modified date')),
            ],
            options={
                'verbose_name': 'issue custom attribute',
                'verbose_name_plural': 'issue custom attributes',
                'ordering': ['project', 'order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IssueCustomAttributesValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1, verbose_name='version')),
                ('attributes_values', taiga.base.db.models.fields.json.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='values')),
            ],
            options={
                'verbose_name': 'issue custom attributes values',
                'verbose_name_plural': 'issue custom attributes values',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskCustomAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('type', models.CharField(choices=[('text', 'Text'), ('multiline', 'Multi-Line Text'), ('richtext', 'Rich text'), ('date', 'Date'), ('url', 'Url'), ('dropdown', 'Dropdown'), ('checkbox', 'Checkbox'), ('number', 'Number')], default='text', max_length=16, verbose_name='type')),
                ('order', models.BigIntegerField(default=taiga.base.utils.time.timestamp_ms, verbose_name='order')),
                ('extra', taiga.base.db.models.fields.json.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date')),
                ('modified_date', models.DateTimeField(verbose_name='modified date')),
            ],
            options={
                'verbose_name': 'task custom attribute',
                'verbose_name_plural': 'task custom attributes',
                'ordering': ['project', 'order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskCustomAttributesValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1, verbose_name='version')),
                ('attributes_values', taiga.base.db.models.fields.json.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='values')),
            ],
            options={
                'verbose_name': 'task custom attributes values',
                'verbose_name_plural': 'task custom attributes values',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserStoryCustomAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('type', models.CharField(choices=[('text', 'Text'), ('multiline', 'Multi-Line Text'), ('richtext', 'Rich text'), ('date', 'Date'), ('url', 'Url'), ('dropdown', 'Dropdown'), ('checkbox', 'Checkbox'), ('number', 'Number')], default='text', max_length=16, verbose_name='type')),
                ('order', models.BigIntegerField(default=taiga.base.utils.time.timestamp_ms, verbose_name='order')),
                ('extra', taiga.base.db.models.fields.json.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date')),
                ('modified_date', models.DateTimeField(verbose_name='modified date')),
            ],
            options={
                'verbose_name': 'user story custom attribute',
                'verbose_name_plural': 'user story custom attributes',
                'ordering': ['project', 'order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserStoryCustomAttributesValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1, verbose_name='version')),
                ('attributes_values', taiga.base.db.models.fields.json.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='values')),
            ],
            options={
                'verbose_name': 'user story custom attributes values',
                'verbose_name_plural': 'user story custom attributes values',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
