# Generated by Django 2.2.17 on 2020-12-03 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issues', '0002_auto_20201203_1019'),
        ('projects', '0002_auto_20201203_1019'),
        ('custom_attributes', '0001_initial'),
        ('tasks', '0001_initial'),
        ('epics', '0001_initial'),
        ('userstories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstorycustomattributesvalues',
            name='user_story',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_attributes_values', to='userstories.UserStory', verbose_name='user story'),
        ),
        migrations.AddField(
            model_name='userstorycustomattribute',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userstorycustomattributes', to='projects.Project', verbose_name='project'),
        ),
        migrations.AddField(
            model_name='taskcustomattributesvalues',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_attributes_values', to='tasks.Task', verbose_name='task'),
        ),
        migrations.AddField(
            model_name='taskcustomattribute',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskcustomattributes', to='projects.Project', verbose_name='project'),
        ),
        migrations.AddField(
            model_name='issuecustomattributesvalues',
            name='issue',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_attributes_values', to='issues.Issue', verbose_name='issue'),
        ),
        migrations.AddField(
            model_name='issuecustomattribute',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuecustomattributes', to='projects.Project', verbose_name='project'),
        ),
        migrations.AddField(
            model_name='epiccustomattributesvalues',
            name='epic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_attributes_values', to='epics.Epic', verbose_name='epic'),
        ),
        migrations.AddField(
            model_name='epiccustomattribute',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epiccustomattributes', to='projects.Project', verbose_name='project'),
        ),
        migrations.AlterIndexTogether(
            name='userstorycustomattributesvalues',
            index_together={('user_story',)},
        ),
        migrations.AlterUniqueTogether(
            name='userstorycustomattribute',
            unique_together={('project', 'name')},
        ),
        migrations.AlterIndexTogether(
            name='taskcustomattributesvalues',
            index_together={('task',)},
        ),
        migrations.AlterUniqueTogether(
            name='taskcustomattribute',
            unique_together={('project', 'name')},
        ),
        migrations.AlterIndexTogether(
            name='issuecustomattributesvalues',
            index_together={('issue',)},
        ),
        migrations.AlterUniqueTogether(
            name='issuecustomattribute',
            unique_together={('project', 'name')},
        ),
        migrations.AlterIndexTogether(
            name='epiccustomattributesvalues',
            index_together={('epic',)},
        ),
        migrations.AlterUniqueTogether(
            name='epiccustomattribute',
            unique_together={('project', 'name')},
        ),
    ]
