# Generated by Django 2.2.17 on 2020-12-02 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.TAIGA_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inviteCode', models.CharField(blank=True, max_length=10, verbose_name='邀请码')),
                ('company', models.CharField(blank=True, max_length=128, verbose_name='公司')),
                ('title', models.CharField(blank=True, max_length=128, verbose_name='职位')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.TAIGA_USER_MODEL)),
            ],
            options={
                'verbose_name': '平台用户',
            },
        ),
    ]
