# Generated by Django 3.0.8 on 2020-07-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activeCode', models.CharField(blank=True, max_length=10, verbose_name='激活码')),
                ('company', models.CharField(blank=True, max_length=128, verbose_name='公司')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='邮箱')),
                ('passwd', models.CharField(max_length=100, verbose_name='服务密码')),
            ],
            options={
                'verbose_name': 'Users',
            },
        ),
    ]
