# Generated by Django 3.0.8 on 2020-07-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': '平台用户'},
        ),
        migrations.RemoveField(
            model_name='users',
            name='activeCode',
        ),
        migrations.AddField(
            model_name='users',
            name='inviteCode',
            field=models.CharField(blank=True, max_length=10, verbose_name='邀请码'),
        ),
    ]
