# Generated by Django 3.0.8 on 2021-02-22 08:35

from django.db import migrations, models
import labManagement.models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_auto_20200805_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, verbose_name='项目名称')),
                ('project_description', models.CharField(max_length=1000, verbose_name='项目简介')),
                ('domain', multiselectfield.db.fields.MultiSelectField(choices=[('能源', '能源'), ('金融', '金融'), ('交通', '交通'), ('电信', '电信'), ('传媒', '传媒'), ('制造', '制造'), ('医疗', '医疗'), ('政务', '政务'), ('科教', '科教'), ('其他', '其他')], max_length=29, verbose_name='领域')),
                ('business', multiselectfield.db.fields.MultiSelectField(choices=[('应用软件', '应用软件'), ('操作系统', '操作系统'), ('大数据', '大数据'), ('分布式存储', '分布式存储'), ('数据库', '数据库'), ('中间件', '中间件'), ('云平台', '云平台'), ('虚拟化', '虚拟化'), ('高性能计算', '高性能计算'), ('ARM原生', 'ARM原生'), ('AI', 'AI'), ('其他', '其他')], max_length=53)),
                ('region', multiselectfield.db.fields.MultiSelectField(choices=[('全球', '全球'), ('中日韩东南亚', '中日韩东南亚'), ('欧美地区', '欧美地区'), ('全国', '全国'), ('粤港澳及华南', '粤港澳及华南'), ('江浙沪及华东', '江浙沪及华东'), ('华北', '华北'), ('东北', '东北'), ('西北', '西北'), ('西南', '西南')], max_length=43)),
                ('location', models.CharField(max_length=1000, verbose_name='项目所在地')),
                ('machine_type', models.CharField(choices=[('虚拟机', '虚拟机'), ('物理机', '物理机'), ('终端', '终端')], max_length=10, verbose_name='资源类型')),
                ('machine_number', models.IntegerField(verbose_name='资源数量')),
                ('machine_config', models.CharField(max_length=255, verbose_name='硬件配置')),
                ('machine_env', models.CharField(max_length=255, verbose_name='软件要求')),
                ('remark', models.CharField(max_length=255, verbose_name='备注')),
                ('start_time', models.DateField(auto_now=True, verbose_name='开始日期')),
                ('end_time', models.DateField(verbose_name='结束日期')),
                ('status', models.CharField(choices=[('等待审批', '等待审批'), ('已开通', '已开通'), ('已回收', '已回收')], max_length=20, verbose_name='资源状态')),
                ('admin_note', models.CharField(max_length=1000, verbose_name='管理员备注')),
                ('admin', models.ForeignKey(on_delete=labManagement.models.get_default_user, related_name='admin', to='users.Users')),
                ('user', models.ForeignKey(on_delete=labManagement.models.get_default_user, to='users.Users')),
            ],
        ),
    ]
