# Generated by Django 3.0.8 on 2021-02-22 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='admin_note',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='管理员备注'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='start_time',
            field=models.DateField(default=datetime.date.today, verbose_name='开始日期'),
        ),
    ]
