# Generated by Django 3.0.8 on 2021-02-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labManagement', '0003_auto_20210222_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='admin_note',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='管理员备注'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='remark',
            field=models.TextField(max_length=255, verbose_name='备注'),
        ),
    ]
