# Generated by Django 3.0.8 on 2021-02-23 06:17

from django.db import migrations, models
import labManagement.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200805_1014'),
        ('labManagement', '0004_auto_20210223_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=labManagement.models.get_default_user, related_name='admin', to='users.Users'),
        ),
    ]
