# Generated by Django 3.0.8 on 2021-03-02 05:53

from django.db import migrations, models
import labManagement.models


class Migration(migrations.Migration):

    dependencies = [
        ('labManagement', '0005_auto_20210223_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='end_time',
            field=models.DateField(default=labManagement.models.next_month, verbose_name='结束日期'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='machine_config',
            field=models.CharField(default='(4)核, (8)G RAM, (200)G SSD存储.', max_length=255, verbose_name='硬件配置'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='machine_env',
            field=models.CharField(default='麒麟V10 Server', max_length=255, verbose_name='软件要求'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='machine_number',
            field=models.IntegerField(verbose_name='设备数量(台)'),
        ),
    ]
