# Generated by Django 3.0.8 on 2021-03-03 02:11

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('labManagement', '0007_auto_20210302_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='cert_file',
            field=models.FileField(blank=True, null=True, upload_to='cert_file', verbose_name='认证证书'),
        ),
        migrations.AddField(
            model_name='resource',
            name='cert_status',
            field=models.CharField(blank=True, choices=[('适配中', '适配中'), ('已适配', '已适配'), ('适配完成', '适配完成')], max_length=20, null=True, verbose_name='资源状态'),
        ),
        migrations.AddField(
            model_name='resource',
            name='cpu_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ft1516', 'FT-1500A/16'), ('ft2064', 'FT-2000+/64'), ('s2500', 'S2500'), ('ft1504', 'FT-1500A/4'), ('ft2004', 'FT-2000/4'), ('d2000', 'D2000'), ('ft2004sec', 'FT-2000/4网安版'), ('d2000sec', 'D2000网安版')], max_length=20, null=True, verbose_name='适配CPU'),
        ),
        migrations.AddField(
            model_name='resource',
            name='product',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='产品名称(如不申请互认证证书无需填写)'),
        ),
    ]
