# Generated by Django 3.0.8 on 2021-03-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labManagement', '0008_auto_20210303_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='cert_status',
            field=models.CharField(blank=True, choices=[('适配中', '适配中'), ('已适配', '已适配'), ('适配完成', '适配完成')], max_length=20, null=True, verbose_name='适配认证状态'),
        ),
    ]
